# .github/workflows/update-readme.yml
name: 游늳 뤯쐃쫧쮏쒫햣햫햦햣 README 쮐햦햩혪

on:
  schedule:
    - cron: '0 0 * * *' # 햨햟햤햢혦햧 햢햣햫혧  00:00 UTC
  workflow_dispatch: # 햪쮏웷쫧 향햟혞혜혝햦혝혧 쒬혞혢햫혞혩

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 햌햩쮏쫧쟴쮏쒫썛쫧쟳 햣쮏햦혝쮐햦혪
        uses: actions/checkout@v3

      - name: 丘뙖잺 뤯쐃쫧쮏쒫햣햫햦햣 README
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: "header, repositories, activity, languages"
          plugin_languages: yes
          plugin_activity: yes

      - name: 游닋 햌쮏쨿쨿쟴 햦향햪햣햫햣햫햦햧
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "游댃 auto: update profile"
          git push
